/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.mainJFrame;

import java.awt.CardLayout;
import model.Person;
import model.PersonDirectory;
import ui.ProfileAreaJPanel;

/**
 *
 * @author Dwaraka Deepika vadd
 */
public class MainJFrame extends javax.swing.JFrame {
    private PersonDirectory personDirectory;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.personDirectory=new PersonDirectory();
        generateDemoDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnManageOrCreate = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(0, 102, 102));

        btnManageOrCreate.setText("Manage or Create Person Profile from here!!");
        btnManageOrCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(btnManageOrCreate)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnManageOrCreate)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrCreateActionPerformed
        // TODO add your handling code here:
        ProfileAreaJPanel panel= 
                new ProfileAreaJPanel(userProcessContainer,personDirectory);
        
        userProcessContainer.add("ProfileAreaJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrCreate;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoDate() {
        
         Person newPerson =personDirectory.addPerson();
        newPerson.setFirstName("Rachel");
        newPerson.setLastName("Green");
        newPerson.setAge(21);
        newPerson.setGender('F');
        newPerson.setSSN("784676374576");
        newPerson.getWorkAddress().setState("MA"); 
       newPerson.getHomeAddress().setPhoneNumber("9837765763");
        newPerson.getWorkAddress().setPhoneNumber("1234567890");
        newPerson.getHomeAddress().setState("MA");
        newPerson.getWorkAddress().setStreetAddress("123 tremont st");
        newPerson.getWorkAddress().setZipCode(21130L);
        newPerson.getWorkAddress().setCity("Boston");
        newPerson.getHomeAddress().setCity("Boston");
        newPerson.getHomeAddress().setStreetAddress("103 Huntington Ave");
        newPerson.getHomeAddress().setZipCode(21340L);
         newPerson.getHomeAddress().setUnitNumber((short)988);
         newPerson.getWorkAddress().setUnitNumber((short)110);
       
        
         Person newPerson1 =personDirectory.addPerson();
        newPerson1.setFirstName("Monica");
        newPerson1.setLastName("Geller");
        newPerson1.setAge(22);
        newPerson1.setGender('F');
       newPerson1.setSSN("62536776344576");
        newPerson1.getWorkAddress().setState("MA"); 
        newPerson1.getHomeAddress().setPhoneNumber("4767765763");
         newPerson1.getWorkAddress().setPhoneNumber("09334567890");
         newPerson1.getHomeAddress().setUnitNumber((short)211);
         newPerson1.getWorkAddress().setUnitNumber((short)311);
         newPerson1.getHomeAddress().setState("MA");
        newPerson1.getWorkAddress().setCity("Boston");
        newPerson1.getWorkAddress().setStreetAddress("123 tremont st");
        newPerson1.getWorkAddress().setZipCode(21030L);
        newPerson1.getHomeAddress().setCity("Boston");
        newPerson1.getHomeAddress().setStreetAddress("204 Huntington Ave");
        newPerson1.getHomeAddress().setZipCode(21350L);
       
        Person NewPerson2 =personDirectory.addPerson();
        NewPerson2.setFirstName("Ryan");
        NewPerson2.setLastName("Reynolds");
        NewPerson2.getHomeAddress().setCity("NewYork");
        NewPerson2.getWorkAddress().setCity("NewYork");
        NewPerson2.getWorkAddress().setStreetAddress("123 Manhattan st");
        NewPerson2.getHomeAddress().setStreetAddress("890 Manhattan st");
        NewPerson2.getHomeAddress().setZipCode(11111L);
        NewPerson2.getWorkAddress().setZipCode(22222L);
        NewPerson2.setAge(34);
        NewPerson2.setGender('M');
        NewPerson2.setSSN("283676374576");
        NewPerson2.getWorkAddress().setState("MA"); 
        NewPerson2.getHomeAddress().setPhoneNumber("2737765763");
        NewPerson2.getWorkAddress().setPhoneNumber("7434567890");
        NewPerson2.getHomeAddress().setState("MA");
        NewPerson2.getHomeAddress().setUnitNumber((short)61);
        NewPerson2.getWorkAddress().setUnitNumber((short)271);
        
        Person NewPerson3 =personDirectory.addPerson();
        NewPerson3.setFirstName("Tony");
        NewPerson3.setLastName("Stark");
        NewPerson3.getHomeAddress().setCity("Dallas");
        NewPerson3.getWorkAddress().setCity("NewYork");
        NewPerson3.getWorkAddress().setStreetAddress("456 Park st");
        NewPerson3.getHomeAddress().setStreetAddress("567 Park st");
        NewPerson3.getHomeAddress().setZipCode(33333L);
        NewPerson3.getWorkAddress().setZipCode(44444L);
        NewPerson3.setAge(49);
        NewPerson3.setGender('M');
        NewPerson3.setSSN("142342353648734");
        NewPerson3.getWorkAddress().setState("NewYork"); 
        NewPerson3.getHomeAddress().setPhoneNumber("9837765763");
        NewPerson3.getWorkAddress().setPhoneNumber("1234567890");
        NewPerson3.getHomeAddress().setState("MA");
        NewPerson3.getHomeAddress().setUnitNumber((short)111);
        NewPerson3.getWorkAddress().setUnitNumber((short)411);
        
        Person NewPerson4 =personDirectory.addPerson();
        NewPerson4.setFirstName("Timothee");
        NewPerson4.setLastName("Chalamet");
        NewPerson4.getHomeAddress().setCity("New York");
        NewPerson4.getWorkAddress().setCity("NewYork");
        NewPerson4.getWorkAddress().setStreetAddress("Park Square");
        NewPerson4.getHomeAddress().setStreetAddress("433 Park Square");
        NewPerson4.getHomeAddress().setZipCode(33333L);
        NewPerson4.getWorkAddress().setZipCode(44444L);
       NewPerson4.setAge(27);
       NewPerson4.setGender('M');
       NewPerson4.setSSN("73246725656327");
       NewPerson4.getWorkAddress().setState("SE"); 
       NewPerson4.getHomeAddress().setPhoneNumber("67456324645");
       NewPerson4.getWorkAddress().setPhoneNumber("89234778235");
       NewPerson4.getHomeAddress().setState("MA");
       NewPerson4.getHomeAddress().setUnitNumber((short)411);
       NewPerson4.getWorkAddress().setUnitNumber((short)461);
        
    }
}
